# This script takes two arguments:
#   $1 denotes the name of a setting file generated by ./src/generating_setting.R
#   $2 is an integer representing the index of a setting in the setting file.
Rscript ./main.R $1 $2
